package com.dariusepure.caractivitylog.ui.cars

val carBrands = listOf(
    "ABARTH", "ACURA", "ALFA ROMEO", "ALPINE", "ASTON MARTIN", "AUDI", "BENTLEY", "BMW", "BUGATTI", "BUICK",
    "BYD", "CADILLAC", "CATERHAM", "CHEVROLET", "CHRYSLER", "CITROËN", "CUPRA", "DACIA", "DAEWOO", "DAIHATSU",
    "DODGE", "DS", "FERRARI", "FIAT", "FORD", "GENESIS", "GMC", "HONDA", "HUMMER", "HYUNDAI", "INFINITI",
    "ISUZU", "JAGUAR", "JEEP", "KIA", "KOENIGSEGG", "LAMBORGHINI", "LANCIA", "LAND ROVER", "LEXUS", "LINCOLN",
    "LOTUS", "LUCID", "MASERATI", "MAYBACH", "MAZDA", "MCLAREN", "MERCEDES-BENZ", "MG", "MINI", "MITSUBISHI",
    "MORGAN", "NISSAN", "OPEL", "PAGANI", "PEUGEOT", "POLESTAR", "PORSCHE", "RAM", "RENAULT", "RIMAC",
    "ROLLS-ROYCE", "ROVER", "SAAB", "SEAT", "SKODA", "SMART", "SSANGYONG", "SUBARU", "SUZUKI", "TESLA",
    "TOYOTA", "TRIUMPH", "TVR", "VAUXHALL", "VOLKSWAGEN", "VOLVO"
).sorted() + "OTHER"
