package com.dariusepure.caractivitylog.ui.cars

data class Country(val name: String, val code: String, val flag: String)

val europeanCountries = listOf(
    Country("Albania", "AL", "🇦🇱"),
    Country("Andorra", "AD", "🇦🇩"),
    Country("Austria", "AT", "🇦🇹"),
    Country("Belarus", "BY", "🇧🇾"),
    Country("Belgium", "BE", "🇧🇪"),
    Country("Bosnia and Herzegovina", "BA", "🇧🇦"),
    Country("Bulgaria", "BG", "🇧🇬"),
    Country("Croatia", "HR", "🇭🇷"),
    Country("Cyprus", "CY", "🇨🇾"),
    Country("Czech Republic", "CZ", "🇨🇿"),
    Country("Denmark", "DK", "🇩🇰"),
    Country("Estonia", "EE", "🇪🇪"),
    Country("Finland", "FI", "🇫🇮"),
    Country("France", "FR", "🇫🇷"),
    Country("Germany", "DE", "🇩🇪"),
    Country("Greece", "GR", "🇬🇷"),
    Country("Hungary", "HU", "🇭🇺"),
    Country("Iceland", "IS", "🇮🇸"),
    Country("Ireland", "IE", "🇮🇪"),
    Country("Italy", "IT", "🇮🇹"),
    Country("Latvia", "LV", "🇱🇻"),
    Country("Liechtenstein", "LI", "🇱🇮"),
    Country("Lithuania", "LT", "🇱🇹"),
    Country("Luxembourg", "LU", "🇱🇺"),
    Country("Malta", "MT", "🇲🇹"),
    Country("Moldova", "MD", "🇲🇩"),
    Country("Monaco", "MC", "🇲🇨"),
    Country("Montenegro", "ME", "🇲🇪"),
    Country("Netherlands", "NL", "🇳🇱"),
    Country("North Macedonia", "MK", "🇲🇰"),
    Country("Norway", "NO", "🇳🇴"),
    Country("Poland", "PL", "🇵🇱"),
    Country("Portugal", "PT", "🇵🇹"),
    Country("Romania", "RO", "🇷🇴"),
    Country("San Marino", "SM", "🇸🇲"),
    Country("Serbia", "RS", "🇷🇸"),
    Country("Slovakia", "SK", "🇸🇰"),
    Country("Slovenia", "SI", "🇸🇮"),
    Country("Spain", "ES", "🇪🇸"),
    Country("Sweden", "SE", "🇸🇪"),
    Country("Switzerland", "CH", "🇨🇭"),
    Country("Ukraine", "UA", "🇺🇦"),
    Country("United Kingdom", "GB", "🇬🇧"),
    Country("Vatican City", "VA", "🇻🇦")
).sortedBy { it.name }
